apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: backend # module defining backend services
build:
  artifacts:
#  - image: gcr.io/abm-edge-test/test-server
#    jib:
#      project: test-server
  - image: gcr.io/abm-edge-test/api-server
    jib:
      project: api-server
  - image: gcr.io/abm-edge-test/inventory
    jib:
      project: inventory
  - image: gcr.io/abm-edge-test/payments
    jib:
      project: payments
  tagPolicy:
    gitCommit: { }
  local:
    concurrency: 0
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/service-configs.yaml
#    - kubernetes-manifests/test-server.yaml
    - kubernetes-manifests/api-server.yaml
    - kubernetes-manifests/inventory.yaml
    - kubernetes-manifests/payments.yaml
