# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cluster_name: "nuc-4"
cluster_index: 3
primary_cluster_machine: true
acm_cluster_name: "store-2-1"
control_plane_ip: "192.168.1.14"
control_plane_ips: [
  "192.168.1.14",
  "192.168.1.15",
  "192.168.1.16"
]
control_plane_vip: "192.168.1.140"
ingress_vip: "192.168.1.141"
load_balancer_pool_cidr: "192.168.1.141-192.168.1.149"
